### ISSUE TITLE
백엔드 코드 컨벤션 작성하기

### ISSUE THREAD

**Issue by yoolf** [CapstoneBase/Yeolmae#3]

**Comment by dbsgh4937** [comment]
**코딩 컨벤션(백엔드)**

- 이름
    - 약어의 중간 단어는 소문자로 표기해서 가독성을 높인다(ex. HttpRequest)
    - 변수명, 클래스명, 메소드 명은 영어와 숫자만 사용 + 상수 사이에는 언더바(_)이용
    - 패키지 이름은 소문자로 구성
    - 클래스 이름은 단어의 첫글자가 대문자인 대문자 카멜표기법 이용
    - 메소드 이름과 변수에는 소문자 카멜표기법 이용
    - 클래스 이름과 인터페이스 이름은 명사를 사용
    - 상수는 대문자와 언더바(_)를 사용한다
    - 테스트 클래스는 Test로 끝나게끔 지정한다

- 선언
    - static import문에만 와일드카드를 허용
    - 메소드는 기능 및 역할별로 분류해 독립적으로 표현한다
    - 클래스는 상수, 인스턴스 멤버 변수, 생성자, 메소드 순으로 작성한다
    - 한 줄에는 하나의 선언문만 작성하고 하나의 변수만 다룬다

- 들여쓰기
    - 1개의 탭 크기 = space 4개와 같게 한다.

- 중괄호
    - 줄의 마지막에 ‘{’를 사용해서 쓰고 새줄을 삽입한다
    - 중괄호를 닫는 ‘}’이 있는 줄에서는 else,catch,finally,while만 선언가능하게 한다
    - 조건, 반복문은 무조건 중괄호를 사용해 코드의 영역을 표시한다

- 줄바꿈
    - package, import에서는 줄바꿈을 하지 않는다
    - 한 줄에 100줄이 넘어가면 줄바꿈한다
    - 줄바꿈 후 들여쓰기는 IDE 자동정렬 기능을 활용한다

- 빈 줄
    - package 선언 후 빈 줄을 넣는다
    - import 그룹을 묶어 선언하고 줄을 삽입한다
    - 메소드 선언이 하나 끝나면 다음 메소드 선언 하는 부분 전 한 빈줄을 넣는다

- 공백
    - 대괄호 ’[’, ‘]’는 ‘;’로 끝나지 않게 한다
    - if, for, while, catch, synchronized, switch 등 제어문 뒤에 소괄호를 선언할 때 앞에 공백을 넣는다(ex. if (max > 0))
    - 식별자와 소괄호 사이에 공백을 넣지 않는다
    - type casting안의 type에서 공백을 넣지 않는다(ex. 잘못된 방법 → String str = ( String ) line;)
    - 주석문 전 후에 공백을 넣는다

**Comment by dbsgh4937** [comment]
**코딩 컨벤션(백엔드)**

- 이름
    - 약어의 중간 단어는 소문자로 표기해서 가독성을 높인다(ex. HttpRequest)
    - 변수명, 클래스명, 메소드 명은 영어와 숫자만 사용 + 상수 사이에는 언더바(_)이용
    - 패키지 이름은 소문자로 구성
    - 클래스 이름은 단어의 첫글자가 대문자인 대문자 카멜표기법 이용
    - 메소드 이름과 변수에는 소문자 카멜표기법 이용
    - 클래스 이름과 인터페이스 이름은 명사를 사용
    - 상수는 대문자와 언더바(_)를 사용한다
    - 테스트 클래스는 Test로 끝나게끔 지정한다

- 선언
    - static import문에만 와일드카드를 허용
    - 메소드는 기능 및 역할별로 분류해 독립적으로 표현한다
    - 클래스는 상수, 인스턴스 멤버 변수, 생성자, 메소드 순으로 작성한다
    - 한 줄에는 하나의 선언문만 작성하고 하나의 변수만 다룬다

- 들여쓰기
    - 1개의 탭 크기 = space 4개와 같게 한다.

- 중괄호
    - 줄의 마지막에 ‘{’를 사용해서 쓰고 새줄을 삽입한다
    - 중괄호를 닫는 ‘}’이 있는 줄에서는 else,catch,finally,while만 선언가능하게 한다
    - 조건, 반복문은 무조건 중괄호를 사용해 코드의 영역을 표시한다

- 줄바꿈
    - package, import에서는 줄바꿈을 하지 않는다
    - 한 줄에 100줄이 넘어가면 줄바꿈한다
    - 줄바꿈 후 들여쓰기는 IDE 자동정렬 기능을 활용한다

- 빈 줄
    - package 선언 후 빈 줄을 넣는다
    - import 그룹을 묶어 선언하고 줄을 삽입한다
    - 메소드 선언이 하나 끝나면 다음 메소드 선언 하는 부분 전 한 빈줄을 넣는다

- 공백
    - 대괄호 ’[’, ‘]’는 ‘;’로 끝나지 않게 한다
    - if, for, while, catch, synchronized, switch 등 제어문 뒤에 소괄호를 선언할 때 앞에 공백을 넣는다(ex. if (max > 0))
    - 식별자와 소괄호 사이에 공백을 넣지 않는다
    - type casting안의 type에서 공백을 넣지 않는다(ex. 잘못된 방법 → String str = ( String ) line;)
    - 주석문 전 후에 공백을 넣는다

**Comment by dbsgh4937** [comment]
**코딩 컨벤션(SQL)**

https://handbook.gitlab.com/handbook/business-technology/data-team/platform/sql-style-guide/

- Case
    - 이름에는 숫자, 문자, 언더바(_)만 사용한다
    - 언더바(_)로 끝나지 않게 하기
    - 쿼리의 길이는 100자가 최대
    - 들여쓰기는 4칸으로 지정
    - 키워드, 타입, 함수는 모두 대문자로 작성
    
- Query
    - 한 줄의 첫 단어는 왼쪽 정렬
    - 키워드나 문장은 추가하려는게 있으면 무조건 다음 줄에 작성
    - 콤마는 항상 왼쪽에 작성
    - 상위 필드와 동일한 라인에 맞도록 정렬하기
    - 중첩 쿼리 사용은 지양한다

- Table
    - 열과 동일한 이름을 지정하지 않는다
    
- Column
    - 항상 단수이름 사용
    - 테이블과 동일한 이름으로 지정하지 않는다
