### ISSUE TITLE
1주차 기능 명세서 작성(5주차)

### ISSUE THREAD

**Issue by yoolf** [CapstoneBase/Yeolmae#7]

**Comment by sooya99** [comment]
# 5주차 기능 명세서
## 5주차에는 회원가입 페이지를 개발할 계획.
### 아이디 입력
1. 아이디 입력
a. 새로운 아이디라면 사용가능 메세지 띄우고 DB에 등록하기
b. 이미 DB에 존재하는 아이디라면 경고 메세지 띄우고 다시 입력받기
2. 비밀번호 입력
a. 비밀번호 양식에 부합한다면 사용가능 메세지 띄우고 DB에 등록하기
b. 비밀번호 양식에 부합하지 않는다면 경고 메세지 띄우고 다시 입력받기
3. 이메일 입력
a. 새로운 이메일 주소라면 사용가능 메세지 띄우고 DB에 등록하기
b. 이미 DB에 존재하는 이메일 주소라면 경고 메세지 띄우고 다시 입력받기
4. 이름 입력
5. 학교와 학과 입력

**Comment by yoolf** [comment]
![image](https://github.com/CapstoneBase/Yeolmae/assets/118517380/8b160d34-b27b-4099-9bb5-dd8350946500)

**Comment by yoolf** [comment]
잘 분류해서 작성해주셨는데 기능명세서는 일반인도 이해할 수 있도록 신경써야 하고 alert, linem, DB같은 용어는 사용자 기준이 아니라 개발하는 사람의 용어이니 다른 용어로 바꿔야 할 것 같습니다!

**Comment by yoolf** [comment]
(수정중)
# 5주차 기능 명세서
## 5주차에는 회원가입 페이지의 기능들을 개발할 계획.
1. 아이디 입력
2. 아이디 중복확인 버튼
  a. 새로운 아이디라면 '사용 가능한 아이디입니다.' 라고 안내합니다.
  b. 이미 존재하는 아이디라면 '이미 존재하는 아이디입니다.' 라고 안내한 뒤 다시 입력하도록 합니다.
3. 비밀번호 입력
  a. 비밀번호 양식에 부합한다면 입력란 아래에 '안전한 비밀번호입니다.' 라고 안내합니다.
  b. 비밀번호 양식에 부합하지 않는다면 입력란 아래에 '안전하지 않은 비밀번호입니다.' 라고 안내합니다.
4. 비밀번호 확인 입력
  a. 비밀번호 양식에 부합한다면 입력란 아래에 '안전한 비밀번호입니다.' 라고 안내합니다.
  b. 비밀번호 양식에 부합하지 않는다면 입력란 아래에 '안전하지 않은 비밀번호입니다.' 라고 안내합니다.
5. 이메일 입력
  a. 이메일 양식에 부합한다면 입력란 아래에 '사용 가능한 이메일 형식입니다.' 라고 안내합니다.
  b. 이메일 양식에 부합하지 않는다면 입력란 아래에 '사용 가능한 이메일 형식이 아닙니다.' 라고 안내한 뒤 다시 입력하도록 합니다.
6. 이메일 중복확인 버튼 
  a. 새로운 이메일 주소라면 '사용 가능한 이메일 주소입니다.' 라고 안내합니다.
  b. 이미 DB에 존재하는 이메일 주소라면 '이미 존재하는 이메일 주소입니다.' 라고 안내한 뒤 다시 입력하도록 합니다. 
7. 이름 입력
8. 학교와 학과 입력   
  
10. 가입하기 버튼
사용자 정보를 다시 입력을 받아야 하는 경우 가입하기 버튼을 누를 수 없게 됩니다.
가입하기 버튼을 누르면 회원가입이 완료되고 이전에 머무르던 화면으로 돌아갑니다. 


[IMAGE]
