### ISSUE TITLE
1주차 기술 명세서 작성(5주차)

### ISSUE THREAD

**Issue by yoolf** [CapstoneBase/Yeolmae#8]

**Comment by dbsgh4937** [comment]
1)
기능 제목 : [회원가입] - 회원가입에 필요한 정보들을 모두 입력받게 설계하고 정보들 중에서 필수/선택적인 항목을 구분한 것을 구현하고 중복 확인이 필요한 부분은 데이터의 중복을 확인해 다른 데이터 값을 요청한다.

구현 기간 : 4.4~4.10

구현 단계 : [개발 중]

데이터베이스 스키마 :
개념 스키마 : 
내부 스키마 :
외부 스키마 :

알고리즘 및 아키텍처 설명 : 
[Back-End]
json 형식으로 Request가 들어오면서 HTTP Method와 회원가입에 대한 API를 입력을 받으면 컨트롤러를 통해 정보를 저장 및 비즈니스 로직을 설계할 수 있는 모델로 Mapping을 하게끔 설계한다. 이후 Mapping된 모델에서 레포지토리 클래스를 통해 DB에 접근해 저장 및 중복 항목에 대해 확인을 한다. 로직들이 다 성공적으로 처리되면 뷰 클래스를 따로 만들어 HTTP Request에 대한 Response값을 json 형식으로 반환 하게 한다.

API 명세서 ->

**Comment by dbsgh4937** [comment]
개념 스키마 : 
아이디, 비밀번호, 이메일, 사용자이름, 학교 및 학과의 속성들은 MEMBER(유저) 테이블에 데이터 타입에 맞게 저장될 것이고 학교 및 학과는 필수조건을 넣지 않을 것이기 때문에 컬럼조건을 NULL 허용으로 설계 후 나머지는 NOT NULL 컬럼 조건을 붙여 저장할 것이다.
DBA에 의해서 구성된다.


[속성 및 데이터 타입에 대한 조건 ERD를 이미지로 설정]

**Comment by dbsgh4937** [comment]
[유저 관리를 위한 회원가입]
[기능 제목] : 회원가입 - 회원들을 관리하고 권한을 부여할 수 있게 회원가입 기능을 제공한다. 회원가입에 필요한 정보들을 모두 입력받게 설계하고 정보들 중에서 필수/선택적인 항목을 구분한 것을 구현하고 중복 확인이 필요한 부분은 데이터의 중복을 확인해 다른 데이터 값을 요청한다.

[구현 기간] : 4.4~4.10

[구현 담당 팀원] : 
[Front-End] : 임수연, 전지후
[Back-End] : 정윤호

[구현 단계] : [개발 중]

[데이터베이스 스키마] : 아이디, 비밀번호, 이메일, 사용자이름, 학교 및 학과의 속성들은 MEMBER(유저) 테이블에 데이터 타입에 맞게 저장하고 학교 및 학과는 필수조건을 넣지 않을 것이기 때문에 컬럼조건을 NULL 허용으로 설계 후 나머지는 NOT NULL 컬럼 조건을 붙여 저장한다.
이는 DBA에 의해서 구성하고 설계된다.

**Comment by dbsgh4937** [comment]
![image](https://github.com/CapstoneBase/Yeolmae/assets/130148224/8b7c64a9-aaa2-44b1-8457-9025b26063de)

**Comment by dbsgh4937** [comment]
![image](https://github.com/CapstoneBase/Yeolmae/assets/130148224/f78bb135-f172-41c8-8675-e772cc54ae58)

**Comment by dbsgh4937** [comment]
[MEMBER 테이블 SQL문]
CREATE TABLE `MEMBER` (
	`MEMBER_ID`	INT	NOT NULL,
	`USERNAME`	VARCHAR	NOT NULL,
	`EMAIL`	VARCHAR	NOT NULL,
	`NAME`	VARCHAR	NOT NULL,
	`PASSWORD`	VARCHAR	NOT NULL,
	`NICKNAME`	VARCHAR	NOT NULL,
	`AUTHORITY`	VARCHAR	NOT NULL,
	`SCHOOL`	VARCHAR	NULL,
	`MAJOR`	VARCHAR	NULL,
	`CREATED_DATE`	VARCHAR	NOT NULL,
	`MODIFIED_DATE`	VARCHAR	NOT NULL
);
